development:
	TWITTER_KEY: 'RnV7JTPNMYmitZHLRmav3vRoA'
	TWITTER_SECRET: '0vyBNqW6eJ6xBAmkjo4M6c7XYu5eaPeBWw0rs3Hd1VB7Wc6REP'
test:
	TWITTER_KEY: 'RnV7JTPNMYmitZHLRmav3vRoA'
	TWITTER_SECRET: '0vyBNqW6eJ6xBAmkjo4M6c7XYu5eaPeBWw0rs3Hd1VB7Wc6REP'
production:
	TWITTER_KEY: 'RnV7JTPNMYmitZHLRmav3vRoA'
	TWITTER_SECRET: '0vyBNqW6eJ6xBAmkjo4M6c7XYu5eaPeBWw0rs3Hd1VB7Wc6REP'
